/* Generated By:JJTree: Do not edit this line. AndCon.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class AndCon extends SimpleNode {
  public AndCon(int id) {
    super(id);
  }

  public AndCon(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ebbb9bb2a64ecc64d74bd8c14a3bc2a4 (do not edit this line) */
