/* Generated By:JavaCC: Do not edit this line. CALParserTreeConstants.java Version 5.0 */
public interface CALParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;
  public int JJTCONST = 3;
  public int JJTFUNCTION = 4;
  public int JJTTYPE = 5;
  public int JJTNPARAMLIST = 6;
  public int JJTMAIN = 7;
  public int JJTSTATEMENT = 8;
  public int JJTASSIGN = 9;
  public int JJTARGASSIGN = 10;
  public int JJTADD = 11;
  public int JJTSUBTRACT = 12;
  public int JJTFUNCRETURN = 13;
  public int JJTANDCON = 14;
  public int JJTORCON = 15;
  public int JJTCOMP = 16;
  public int JJTEQUAL = 17;
  public int JJTNOTEQUAL = 18;
  public int JJTLESSTHAN = 19;
  public int JJTLESSTHANEQUALTO = 20;
  public int JJTGREATERTHAN = 21;
  public int JJTGREATERTHANEQUALTO = 22;
  public int JJTARGLIST = 23;
  public int JJTID = 24;
  public int JJTNUMBER = 25;
  public int JJTBOOL = 26;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Var",
    "Const",
    "Function",
    "Type",
    "NParamList",
    "Main",
    "Statement",
    "Assign",
    "ArgAssign",
    "Add",
    "Subtract",
    "FuncReturn",
    "AndCon",
    "OrCon",
    "Comp",
    "Equal",
    "NotEqual",
    "LessThan",
    "LessThanEqualTo",
    "GreaterThan",
    "GreaterThanEqualTo",
    "ArgList",
    "ID",
    "Number",
    "Bool",
  };
}
/* JavaCC - OriginalChecksum=144d540c0188cba8c1a18f7f82954570 (do not edit this line) */
