/* Generated By:JJTree: Do not edit this line. GreaterThanEqualTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class GreaterThanEqualTo extends SimpleNode {
  public GreaterThanEqualTo(int id) {
    super(id);
  }

  public GreaterThanEqualTo(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=efcf09a958e87fddfd608784fe0489fd (do not edit this line) */
