/* Generated By:JJTree: Do not edit this line. LessThanEqualTo.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class LessThanEqualTo extends SimpleNode {
  public LessThanEqualTo(int id) {
    super(id);
  }

  public LessThanEqualTo(CALParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CALParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4321a8db3880db032b0b1997d378e6d7 (do not edit this line) */
